### ISSUE TITLE
Add grunt config

### ISSUE THREAD

**Issue by robneu** [wpsitecare/wp-featherlight#1]
I made this pretty quickly, so I haven't automated the script or style build processes yet. I'd like to add a few basic options to the plugin eventually so this would probably be helpful.

**Comment by michaelbeil** [comment]
What is typical for you?

**Comment by robneu** [comment]
I don't really have a typical build for plugins right now. I have one that I use for themes, but I think it's overly complicated for most plugins since they usually don't load as much front-end stuff as a theme.

I'm hoping to get a somewhat standardized build put together sometime in the next few days and integrate it here and in our [example plugin](https://github.com/wpsitecare/example-plugin) that I use as a starting point for most of our internal stuff.
