### ISSUE TITLE
Consider Loading Unpacked Scripts by Default

### ISSUE THREAD

**Issue by robneu** [wpsitecare/wp-featherlight#14]
Right now we load a packed and minified version of our scripts by default. You can see how this is done [here](https://github.com/wpsitecare/wp-featherlight/blob/develop/includes/class-scripts.php#L87-L108).

The main reason for this is in my experience, most WordPress users don't do anything to combine scripts. There are plugins which can do it, but most of them are kind of confusing and somewhat ineffective. The vast majority of websites out there just load scripts in whatever way they're set up to load in their theme or plugins.

Loading our scripts this way means most users will have a better, faster experience with our plugin. The unfortunate side effect is that some may experience conflicts with other plugins that use Featherlight. The issue was discussed on the [Google Maps Builder](https://github.com/WordImpress/google-maps-builder/issues/11) repo but I'd like to hear some arguments either for or against the method we're using.

I feel that the way we're loading scripts benefits users and creates a slight obstacle for other developers, but not one that should really be a big deal since we have so many filters available to them. I could be wrong about this though. 

Thoughts? Opinions? Arguments? FLAME WARS??!

**Comment by chriswallace** [comment]
I hate plugins that load combined assets by default. I don't mind loading minified scripts, though I do prefer to leave that to plugins that will minify/concatenate files for you. Many popular caching plugins offer some form of script/style manipulation and there are a number of standalone plugins that can do it quite well without much hassle.

**Comment by robneu** [comment]
Why do you hate them? Is it because you don't like to deal with the extra overhead as a developer or is there a reason that they're a problem as a user?

Those plugins may exist, but using them is not the norm, unfortunately.

**Comment by royboy789** [comment]
I don't think it is a @robneu issue, I think it is a WordPress issue. There needs to be ab etter way of seeing if a certain library JS file or CSS is set to be enqueued. 

Check out this code I help re-write for Google Maps Builder -
https://github.com/WordImpress/google-maps-builder/blob/master/public/class-wordpress-google-maps.php#L548-L586

Unfortunately the `global $wp_scripts;` global is only available in the wp_head callback as far as I know (with all plugin enqueue's) - so I think it is important to look at other ways of doing this type of logic BEFORE the `wp_enqueue_scripts`action.. but hopefully a lot better and more consistent then a string search

**Comment by chriswallace** [comment]
I personally like to know that a plugin isn't sneaking 15,000 lines of code into a giant JS file. It's helpful to be able to view the scripts being loaded and see the names of each file and understand what JS plugins/dependencies were just added when I activated a plugin.

**Comment by robneu** [comment]
@royboy789 I agree it's mainly a WordPress problem, but it's also one that probably won't be fixed anytime soon.

I was planning on implementing something along those lines for #13, but haven't written any code yet so I think I may just steal some of yours. :grinning:

**Comment by robneu** [comment]
@chriswallace I could be wrong for assuming this, but I'm pretty sure you're an edge case. Most WordPress users probably aren't even aware of the scripts being added by any given plugin. 

The idea that the script handles and full source code would be helpful to most people seems far-fetched to me. If someone understood all that, why are they even using a plugin at all? Wouldn't it be simpler for them to just add the JavaScript to their theme themselves?

**Comment by mathetos** [comment]
I actually find it much more bothersome when I do try to use a minification plugin and find that a prominent plugin's JS doesn't minify well. Having them pre-minified makes them easier to coorperate with minification plugins.

Plus, the truth is, you are loading scripts on the front-end, and it's best practice for assets to be minified. Minifying by default plays better with minification plugins, and is best practice when no minification is happening.

But serious bonus points for having settings to separate them, I think that's awesome.

**Comment by royboy789** [comment]
The issue with minification plugins isn't minification, its concatenation, especially when you are not wrapping everything in an object. but yes, why would I trust a developer to not also throw in useless minified libraries, like another minified jQuery library.

Also the issue is not the 1% of dev's its the 23% of the web that has 10+ plugins running on their blog/business/personal site.

**Comment by ryandonsullivan** [comment]
My .02 is that catering to developers is a mistake for this plugin. The vast majority of WordPress users don't even know what minification or concatenation are, so including unpacked scripts is just going to add more unnecessary bloat to the front end of their site, which not only sucks for performance, but also sucks coming from a plugin that claims to be ultra lightweight. Developers can dequeue and concatenate if they really want to. There are methods to do that easily. Users on the other hand will likely never implement any kind of minification or concatenation solution on their own, so doing this for them in our plugin seems like a win to me.

P.S. Not sure if @royboy789 knows this or not but this WordPress plugin is based on a popular jQuery plugin that's also called Featherlight. 🌟

**Comment by royboy789** [comment]
As far as "this plugin" no - I think it is fine as-is. 

@ryandonsullivan really? a jQuery plugin, you don't say?

**Comment by robneu** [comment]
I think we're going to stick with the way we're doing things, at least for this plugin. Thanks for the input everyone!
