### ISSUE TITLE
Improve Readme & Documentation

### ISSUE THREAD

**Issue by thefuxia** [wpsitecare/wp-featherlight#18]
The readme says:

> When installed, the plugin will automatically display all standard WordPress images and galleries in a simple, minimalistic lightbox popup.

This isn't true for standard galleries.

Using WordPress 4.4-alpha-33702 and _Twenty Ten_, I have created a simple gallery: `[gallery ids="570,569,568"]`.

While other images on the same page _are_ shown in the lightbox, the gallery images are not. Clicking them leads to the attachment page.

There are no errors in the browser console, no other conflicting plugins are active. 

Tested in:
- Opera Presto 12.17
- Firefox Developer Edition 42.0a2 (2015-08-15)
- Vivaldi 1.0.219.50 (Blink 537.36)

**Comment by robneu** [comment]
That's expected behavior, but the documentation is probably misleading. It will only light box gallery images when linking to the media files.

**Comment by thefuxia** [comment]
Oh, indeed, that works. Yes, that should be explained in the readme. :)

**Comment by robneu** [comment]
Thanks for taking the time to test it! Really appreciate it. 

We'll make sure that's more clear before we roll out this latest version. Let us know if you run into any other issues or see anything horrible in the code. ;)
