### ISSUE TITLE
Make the deactivation checkbox translatable

### ISSUE THREAD

**Issue by thefuxia** [wpsitecare/wp-featherlight#19]
There is a string for the deactivation per post in the [current `pot` file](https://github.com/wpsitecare/wp-featherlight/blob/fa837e5983394a99deaeb1821d41705cf1c9791a/languages/wp-featherlight.pot):

> Disable Lightbox on this %s

The problem is that each post type's name can be gendered in many languages. French and German are two examples. Depending on the gender of the post type – which is unknown for the translator – the _this_ needs a different translation.

`page` is female in German _(Seite)_, `post` is male _(Beitrag)_. So the translation would be for:
- `page`: Die Lightbox für _diese_ Seite abschalten.
- `post`: Die Lightbox für _diesen_ Beitrag abschalten.

I can just write _Die Lightbox abschalten._ This works, and it is clear enough. But I think it should be changed in the original string too, because other translators might run into the same problem.

**Comment by robneu** [comment]
I think the simpler string should be clear enough and avoid these issues in other languages. If that seems like it'll work, I'll go ahead and close this out.
