### ISSUE TITLE
Do not load translation files on every admin request

### ISSUE THREAD

**Issue by thefuxia** [wpsitecare/wp-featherlight#22]
`\WP_Featherlight::run()` loads the translation files for every admin request, including all AJAX requests, updates, dashboard and so on. This is a waste of resources. Much less than many other plugins, but still …

There are only two places where the files need to be loaded:
1. The plugin page, hook: `admin_head-plugins.php`.
2. When the checkbox label is displayed. This could be done directly in that place.

**Comment by robneu** [comment]
I've often wondered about how to reduce the overhead with regard to loading translation files, but I'm relatively unfamiliar with how the translation functions in WordPress actually work. So far the best I've been able to do is isolate it to the admin or front end based on how the strings are being used.

Do you know of any code that would be a good example for using `load_plugin_textdomain` in a more contextual way like this? Is it safe to just use it directly on those pages by checking a page hook or `get_current_screen`?

**Comment by thefuxia** [comment]
You could move the language handling into its own class (it _is_ a separate task) and then either register its `load()` method for specific hooks and/or pass the object instance into the _View_ object where it can be called directly.

Here is an example for such a class: [toscho/t5-libraries/Core/I18n/Language_Loader.php](https://github.com/toscho/t5-libraries/blob/4105a4756f49a22aa1fd3855d526063ce4787d0e/Core/I18n/Language_Loader.php).

**Comment by thefuxia** [comment]
Why do you always put callback registration and business logic into the same class? These are separate tasks. When you'd move the registration to the controller `WP_Featherlight_Admin_Meta`, you could reuse the language loader in other projects. A single business object shouldn't know anything about the rest of the control flow.

**Comment by robneu** [comment]
> Why do you always put callback registration and business logic into the same class?

Mostly ignorance, probably. Would you mind showing me an example of how they should be separated?

**Comment by thefuxia** [comment]
A very simple example is the [`Mlp_User_Settings_Controller`](https://github.com/inpsyde/multilingual-press/blob/e5bc6d9c68025f369feb5343108b50f4b5d56419/inc/user-setting/Mlp_User_Settings_Controller.php). It gets the _View_ and the save callback (a model) per constructor and registers just the callbacks for the hooks. You can reuse the _View_, the _Model_ and even the _Constructor_. The latter is something that I don't follow very strictly in most projects, but keeping the callback registration separate from everything else – view and business models – is very useful, because the resulting code is easy to read, to test and to change.

That means also that there should be _no code_ executed in a file with a class declaration: `defined( 'ABSPATH' ) || exit;` doesn't belong to such a file.

**Comment by robneu** [comment]
Hmm... I think I follow, but I'm not 100% sure I understand how to implement something like that correctly. It's probably more complicated than usual since this plugin doesn't autoload classes right now.

I've also run up against issues with passing dependencies around in plugins that are more strictly OOP/MVC like you're describing. The way I'm handling it in this plugin is probably pretty hacky/stupid... Actually, even the newer methods I've implemented seem problematic. I looked into using a dependency injection container but it seems kind of difficult to do in PHP 5.2.

I'll read through the code in the plugin you linked to a bit and see if I can wrap my head around it for the next release. This plugin is pretty basic, so it's probably the best one for me to learn more about this stuff before trying to implement it on larger projects.

**Comment by thefuxia** [comment]
Yeah, no need to hurry. :) Stay away from DI containers as long as possible. It is too easy to make the code more difficult to read with those. Usually, you set up dependencies via [interfaces](http://wpkrauts.com/2013/how-to-build-flexible-php-interfaces/). That's enough for most cases.

DI containers are used when the object creation is expensive and should wait as long as possible. You can get around that problem often with smaller objects or a different architecture. Anyway, this will never be a problem in this plugin.

**Comment by robneu** [comment]
Ah! That article on interfaces is really helpful. I'll work through this as soon as I have a chance. Thanks again for all the help. I'm closing this out for now and I'll work on the code cleanup in a new issue.
