### ISSUE TITLE
Gallery transition could be smoother

### ISSUE THREAD

**Issue by robneu** [wpsitecare/wp-featherlight#27]
By default, featherlight transitions by fading the current image out but doesn't perform a fade-in when the next image loads. This is a little odd, although it's never bothered me.

One of our users [reported this as an issue](https://wordpress.org/support/topic/animation-only-fadeout), so I think it's probably worth improving the transition a bit.

**Comment by NateWr** [comment]
For what it's worth, I actually really like the default transition. There's enough signalling in the transition to not be jarring, and the _pop_ as a new image comes in feels snappy and exciting.

**Comment by robneu** [comment]
I've never minded it either. This has only ever come up once since the plugin was released, so I'm guessing it's probably not a huge sticking point for most people. I might just leave it as-is.
