### ISSUE TITLE
Captions strip out HTML

### ISSUE THREAD

**Issue by robneu** [wpsitecare/wp-featherlight#33]
I didn't even know that WordPress supported HTML within captions, but since it does we should probably stop using `.text` in favor of `.html`.

**Comment by robneu** [comment]
I'm hesitant to do anything here because it feels like potential XSS territory to me. I'm not familiar enough with how XSS attacks are avoided in JS to be able to do this safely. If anyone else has any ideas how to do this without introducing a potential security issue, please let me know.

**Comment by michakrapp** [comment]
Just came across here because I want to show a link / button as description.
Any news on this?
Any chance for me to achieve that?

**Comment by michakrapp** [comment]
Created pull request https://github.com/wpsitecare/wp-featherlight/pull/38

**Comment by robneu** [comment]
Thanks for the PR @michakrapp but I'm still a bit hesitant to add this due to the reasons stated [here](https://stackoverflow.com/a/15928704).

http://www.shafigullin.pro/XSS/jquery.html looks interesting, but unfortunately I don't have the time to dig in on this right now. If you'd like to, please document your findings so that I can review them before merging.

**Comment by michakrapp** [comment]
Thanks for your reply.
Your second link does not work.

But after reading your linked SO answer I revamped the code to use `innerHTML` as stated in there.

Tested the code and it worked. Insert script with alert() gets to this and is not called.
![caption xss](https://user-images.githubusercontent.com/5496691/30320027-c06c6e28-97b1-11e7-825a-980a4db014c7.PNG)


changing:
```
$( '<div class="caption">' ).text( caption.text() ).appendTo( object.find( '.featherlight-content' ) );
```

to:
```
$( '<div class="caption">' ).appendTo( object.find( '.featherlight-content' ) );
var captionElement = document.getElementsByClassName( 'caption' )[0];
captionElement.innerHTML = caption.html();
```

**Comment by michakrapp** [comment]
Updated the PR https://github.com/wpsitecare/wp-featherlight/pull/38

**Comment by michakrapp** [comment]
Thanks for the Plugin update. HTML in Captions work
