### ISSUE TITLE
Setting overflow: auto on .featherlight-content

### ISSUE THREAD

**Issue by NateWr** [wpsitecare/wp-featherlight#35]
I've stripped out the styles from `wp-featherlight` to use in my new site design, just so I can bundle the styles in a single file. 

I also use featherlight to display a few modals with HTML content, like my pricing tables. For this, `.featherlight-content` should scroll when content exceeds viewpoint height as it does in [the demo](http://noelboss.github.io/featherlight/). But using the stripped down styles here I found that it didn't.

It turns out that you use `overflow: visible` on `.featherlight-content` here: 

https://github.com/wpsitecare/wp-featherlight/blob/develop/css/src/partials/_base.scss#L40

The featherlight CSS uses `overflow: auto` instead and it looks like it's been that way for a long time:

https://github.com/noelboss/featherlight/blob/master/src/featherlight.css#L54

I've changed it for my own needs but I was curious if you remember why you made that change, if there's a reason I ought to avoid `overflow: auto` in this case.

**Comment by robneu** [comment]
Hmm... it's been so long that I can't remember the specific reason now. I think it was something related to scrollbars showing up when they really weren't supposed to. There are quite a few issues with the default featherlight CSS that have been left unaddresed by the author so I opted to almost completely re-style it for our purposes.

**Comment by NateWr** [comment]
Makes sense. I know older versions of IE were a nightmare with scrollbars. I'll leave it be for now since I'm mostly targeting newer browsers. Cheers for the quick response.
