### ISSUE TITLE
Lightbox background doesn't load on first click

### ISSUE THREAD

**Issue by joecue** [wpsitecare/wp-featherlight#37]
I have a media gallery with 6 items in it.  When I click for the first time on an image I get the larger image, but I don't get the semi transparent black background.  When I click where the background overlay should be the lightbox closes and I can go back to the media gallery and choose a different photo, now the overlay loads.  Doesn't matter if it's the first photo in the gallery or the last, but it's only with the first one I click.  I've tried reloading the page several times, I've even tried incognito mode, nothing seems to resolve the issue.

I'm running 4.7.5 and a custom developed theme from underscores.  I don't have any other lightbox type plugins installed.

**Comment by ryandonsullivan** [comment]
Hey @joecue.

This sounds like a behavior that's a conflict with something else. Either your theme or another plugin.

Have you gone through the standard troubleshooting steps of disabling all plugins other than Featherlight to narrow down a possible culprit? And changing to a default WP theme?

Also, are you seeing any errors in the console on your browser? They may be able to show some additional detail too.

We haven't heard of this type of behavior anywhere else so my gut is that it's an isolated issue but always good to be sure.

**Comment by joecue** [comment]
Thanks Ryan...

I'm not see any console errors, and the odd thing is it's working in both my dev and test environments as expected.  And test mirrors prod.

Very strange.

**Comment by ryandonsullivan** [comment]
Any luck this this Joe? I've tried to reproduce it a number of different ways and haven't been able to. We also have had any other reports of the same behavior, unfortunately. I'm going to close the issue for now but if you have more info you think might be helpful go ahead and reopen and we can dig in some more. Thanks!
