### ISSUE TITLE
Remove Expand Icon and Feature

### ISSUE THREAD

**Issue by haslamjd** [wpsitecare/wp-featherlight#40]
When a thumbnail image is clicked on and the larger image opens in a new wp-featherlight window, there is an "expand the image" (X) icon in the upper right hand corner that looks like a "Close" this window icon (which is actually in the lower right hand corner). This is upper right icon is confusing our visitors, and the images on our site don't need to be expanded to full frame. 

Is there a way to remove this icon (expand feature) so that our visitors don't get confused thinking that this is a "close" window icon?

Thanks.

**Comment by robneu** [comment]
Do you have a screenshot? We don't include an expand icon or feature by default, so maybe something in your theme or another plugin is doing something?

**Comment by haslamjd** [comment]
Here is a screenshot...
![featherlight](https://user-images.githubusercontent.com/33100496/32017313-8d026bde-b983-11e7-84b3-1a331b49d77f.jpg)

**Comment by robneu** [comment]
That's not featherlight. You must be using another plugin for lightboxing.

**Comment by haslamjd** [comment]
Funny, that is the only lightbox plugin I have installed and activated.

**Comment by robneu** [comment]
The lightbox may be coming from your theme or a gallery plugin. Whatever it is, it's not featherlight so I'm not really able to help out on this one.

If you have a link to the site in question I might be able to help narrow it down a bit.
