### ISSUE TITLE
SVG support missing

### ISSUE THREAD

**Issue by strarsis** [wpsitecare/wp-featherlight#43]
SVG images correctly cause the Featherlight box to open - but no SVG is shown - some HTML attributes / styles are missing. [Easy FancyBox](https://wordpress.org/plugins/easy-fancybox/) does this correctly, the code could be re-used by this plugin.

**Comment by robneu** [comment]
We don't officially support SVG because WordPress core does not. I did allow it to be recognized as an image type, but have not added any specific handling for it beyond that. If you'd like to submit a pull request to improve support, I'll take a look.
