### ISSUE TITLE
calling https

### ISSUE THREAD

**Issue by mequel** [wpsitecare/wp-featherlight#44]
![25440285_915093168647831_6197617349440441563_o](https://user-images.githubusercontent.com/34649642/34104826-c2486926-e43d-11e7-9b2c-53b99c702d69.jpg)

Mixed content error. Can anyone point to why?

**Comment by robneu** [comment]
This is a configuration issue with your site and doesn't have anything to do with WP Featherlight. Check to make sure your site's URL is correct in the WordPress database.
