### ISSUE TITLE
Compability with Latest Wordpress 4.9.4? 

### ISSUE THREAD

**Issue by aparentMMS** [wpsitecare/wp-featherlight#48]
Hi there, are you planning to release an update for the latest WP release? It doesn't show that it's been tested with latest WP in the plugin repository.

**Comment by ryandonsullivan** [comment]
Hey there! It's certainly still compatible with the latest version of WordPress. It just hasn't been updated to say that on WordPress.org. We'll update compatibility in a future release. Thanks.

**Comment by aparentMMS** [comment]
Great, thanks!
