### ISSUE TITLE
Gallery with <a> element in caption causes extra navigation clicks/swipes

### ISSUE THREAD

**Issue by proudfoot** [wpsitecare/wp-featherlight#49]
When I add an <a> element to a caption an extra navigation click is added between the slide with the caption and whatever is next in the gallery. 

[Here a gallery](https://sloweye.net/customer-photos-small-prints/) with an attribution link in the first caption that is adding a click

Is there a way to limit navigation to only the first <a> per gallery item?

**Comment by ryandonsullivan** [comment]
Hmmm, this isn't a behavior we've seen before. Your theme is bundling a few JS libraries that may be causing this behavior. Do you experience this when using a default WordPress theme?

**Comment by proudfoot** [comment]
Here is [the same gallery on a copy of the site](https://staging2.sloweye.net/customer-photos-small-prints/) running Twenty Fifteen with no plugins other than WP-Featherlight. I'm getting the same extra click in the navigation.

**Comment by proudfoot** [comment]
Whoops, that was an accidental close...

**Comment by proudfoot** [comment]
@ryandonsullivan
I found [this support thread](https://wordpress.org/support/topic/making-the-gallery-functionality-work-on-pagesposts/) in which a user suggests replacing `".gallery-item a"` with `"a[data-featherlight='image']" `

I tried this and it resolves the extra click that was happening when `buildGalleries` adds every `a` to `$galleryItems` including any present  in captions

In case it's useful, I've submitted a pull request. Wasn't able to minify, though.

**Comment by robneu** [comment]
This should be fixed in the next release. If you're able, please test our development branch and let me know if the problem has been taken care of.

**Comment by proudfoot** [comment]
@robneu 
Thanks! I've installed the development branch on [a copy of the site and the gallery navigation now works as expected](https://staging2.sloweye.net/customer-photos-small-prints/).

**Comment by robneu** [comment]
Fantastic! It looks like we may need to apply some styling to links in captions as well.
