### ISSUE TITLE
Admin Metabox String Translation

### ISSUE THREAD

**Issue by robneu** [wpsitecare/wp-featherlight#5]
This was pointed out in #4 and should be fixed to ensure translations can be made accurately.

**Comment by robneu** [comment]
@GaryJones Can you double check this to see if I've done it correctly? It looks alright to me, but I'm not 100% sure.

**Comment by GaryJones** [comment]
A few slight improvements, handled with a PR in #8.

**Comment by robneu** [comment]
Merged. Thanks!
