### ISSUE TITLE
Gallery caption class

### ISSUE THREAD

**Issue by giles247** [wpsitecare/wp-featherlight#50]
Has an issue that captions were not showing for me because my captions did not have .wp-caption-text class as I was using 'cleaner-gallery' option from Hybrid framework that did not add this class. When I changed lines 84 and 89 in wpFeartherlight.js to look for .gallery-caption instead it worked again.

I guess issue may be with 'cleaner-gallery' in terms of which is preferred class?

**Comment by robneu** [comment]
Hey redactuk,

At the moment we only support the WordPress core and Jetpack gallery caption classes. As best I can tell, there's not really any good way to support a large amount of caption classes without bloating the plugin. If you have any ideas, let me know.
