### ISSUE TITLE
Enable ONLY if checked.

### ISSUE THREAD

**Issue by wpjohnny** [wpsitecare/wp-featherlight#61]
Hi and thank you for the great plugin (it is beautiful!),

I had similar idea as https://github.com/cipherdevgroup/wp-featherlight/issues/53 ...but I'm willing to settle for something much easier...

- I want default behavior to be DISABLED, and then ENABLED only when the checkbox is selected in document settings. 
- Can we have some like reverse behavior setting? 

If not, I'll probably fork this plugin to do so but I prefer to have all credit and focus go to this original plugin.

**Comment by ozzyrod** [comment]
Thanks for the suggestion @wpjohnny. We're trying to keep the plugin simple and this would add a level of complexity to the plugin that might turn some people off of it. We like that it just works out of the box and you only have to worry about turning it off on certain pages.

Forking it to work the way you want is probably your best bet.
