### ISSUE TITLE
Single image and galleries in post

### ISSUE THREAD

**Issue by schwantuschke** [wpsitecare/wp-featherlight#65]
It's possible to show single images and galleries in post in one lightbox.
In this [old thread](https://wordpress.org/support/topic/single-pics-and-gallerys-in-a-post/) are no answer and [here](https://stackoverflow.com/questions/41554999/how-can-i-make-wp-featherlight-work-with-images-like-with-galleries) is an hack, but I don't want to change the code.

(I create a [thread](https://wordpress.org/support/topic/single-pics-and-gallery/) in wordpress.com forum, but I don't know if anyone is reading this)

**Comment by ozzyrod** [comment]
We know it's possible, but most people don't want to to paginate single images (i know I don't). If you absolutely need it, you should try and find another lightbox plugin,
