### ISSUE TITLE
Add a Visible Loader

### ISSUE THREAD

**Issue by robneu** [wpsitecare/wp-featherlight#7]
Featherlight [allows](https://github.com/noelboss/featherlight/#configuration) for a loader to be displayed while content is being fetched, but doesn't use anything other than a class name change by default. 

We should probably add a font icon or SVG loader to make it obvious when there's a problem fetching content. This is particularly true if we're going to implement #6.

**Comment by GaryJones** [comment]
Definitely prefer SVG over font icon.

**Comment by robneu** [comment]
It looks like this can be done with pure CSS, so I'm taking a stab at that route before adding any extra overhead.
